# EZ A TELJES ÉS VÉGLEGES VERZIÓ, MINDEN CSAPATLEÍRÁS A FELHASZNÁLÓTÓL SZÁRMAZIK
import sqlite3
import os

DB_FILE = "nfl_akademia.db"

# Töröljük a régi adatbázis fájlt, ha létezik, hogy teljesen tiszta alapról induljunk
if os.path.exists(DB_FILE):
    os.remove(DB_FILE)
    print(f"A régi '{DB_FILE}' adatbázis sikeresen törölve.")

# Csatlakozás az új, üres adatbázishoz
conn = sqlite3.connect(DB_FILE)
cursor = conn.cursor()

# --- Táblák létrehozása ---
cursor.execute('''
    CREATE TABLE categories (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL UNIQUE
    )
''')
cursor.execute('''
    CREATE TABLE entries (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        term TEXT NOT NULL,
        description TEXT NOT NULL,
        category_id INTEGER,
        FOREIGN KEY (category_id) REFERENCES categories (id)
    )
''')
print("Adatbázis táblák sikeresen létrehozva.")

# --- Kategóriák és Bejegyzések Hozzáadása ---
try:
    # Kategóriák
    categories_to_add = [
        ("Szabályok",), 
        ("Kifejezések",),
        ("Játékosok",),
        ("Csapatok (AFC)",), 
        ("Csapatok (NFC)",)
    ]
    cursor.executemany('INSERT OR IGNORE INTO categories (name) VALUES (?)', categories_to_add)
    print("Kategóriák hozzáadva.")

    # Bejegyzések (Teljes, Végleges Lista, a felhasználó által frissített leírásokkal)
    entries_to_add = [
        # === Szabályok (category_id = 1) ===
        ("Challenge (Kihívás)", "Az edzőknek meccsenként kétszer van lehetőségük egy piros zászló bedobásával videóbírói visszajátszást kérni egy vitatott ítéletre. Ha a kihívás sikeres, az ítéletet megváltoztatják, és az edző megtarthatja a lehetőséget. Ha a kihívás sikertelen, az ítélet marad, és az edző elveszít egy időkérést. Ez egy stratégiai elem, amit a meccs kritikus pillanataiban használnak.", 1),
        ("Delay of Game (Játék késleltetése)", "A támadó csapatnak meghatározott ideje van (általában 40 másodperc) elindítani a következő játékot, amit a 'play clock' mér. Ha ez az óra lejár, mielőtt a játék elindulna, a csapat 5 yardos büntetést kap. Ez a szabály biztosítja a játék folyamatosságát és megakadályozza az időhúzást. A nagy vendég szurkolói hangzavar gyakran okoz ilyen büntetést, mert a támadók nem hallják egymást.", 1),
        ("Down (Kísérlet)", "A támadó csapatnak négy kísérlete (down) van arra, hogy a labdával legalább 10 yardot előrehaladjon. Minden egyes játék, ami a labda hátraadásával (snap) kezdődik, egy 'down'-nak számít. A TV-s közvetítéseken gyakran látni kiírásokat, mint '1st & 10', ami első kísérletet és 10 megteendő yardot jelent. Ez a rendszer adja a játék alapvető ritmusát és stratégiai mélységét.", 1),
        ("Extra Pont (PAT)", "Egy sikeres touchdown (6 pont) után a pontszerző csapatnak lehetősége van egy bónuszpontra. Az extra pont, vagy PAT (Point After Touchdown), egy rövid rúgás a kapura, ami 1 pontot ér. Ez régen szinte automatikus volt, de a távolság növelésével mára egy izgalmasabb, de még mindig nagy százalékban sikeres játékelem. A csapat dönthet úgy is, hogy inkább a kockázatosabb kétpontos kísérletet választja.", 1),
        ("False Start (Rossz rajt)", "Ez egy gyakori, 5 yardos büntetés, amit a támadócsapat ellen ítélnek. Akkor történik, ha egy támadójátékos (az irányítón kívül) a labda játékba hozatala (snap) előtt megmozdul. Ez a szabály megakadályozza, hogy a támadók igazságtalan előnyhöz jussanak a védőkkel szemben. Egyetlen rossz mozdulat is hátrányos helyzetbe hozhatja a támadókat.", 1),
        ("Field Goal (FG)", "A mezőnygól 3 pontot ér, és általában akkor próbálkozik vele egy csapat, ha a negyedik kísérletnél járnak, de túl messze vannak egy újabb első kísérlethez, viszont elég közel a kapuhoz. A rúgójátékosnak (kicker) a labdát a két függőleges kapufa és a keresztléc fölé kell rúgnia. A mezőnygólok, különösen a meccs végén, gyakran döntenek a győzelemről, így a rúgójátékosok idegei aranyat érnek.", 1),
        ("First Down (Első kísérlet)", "A 'first down' a támadósorozat motorja. Amikor a támadócsapat sikeresen megteszi a szükséges 10 (vagy több) yardot a rendelkezésére álló négy kísérleten belül, jutalmul egy teljesen új, négy kísérletből álló sorozatot kap. Ezzel a labdabirtoklás folytatódik, és a csapat tovább haladhat a célterület felé. A cél tehát mindig az, hogy a csapat folyamatosan 'first down'-okat érjen el, fenntartva a támadást.", 1),
        ("Fumble", "A 'fumble' egy élő labdavesztés, ami akkor történik, amikor a labdát cipelő játékos elejti azt, mielőtt a földet érné (szerelés után). A labda 'szabaddá' válik, és bármelyik csapat játékosa megszerezheti, aki először rávetődik. Ez a játék egyik legkaotikusabb és legizgalmasabb pillanata lehet, mivel egyetlen mozdulattal az ellenfélhez kerülhet a támadás joga, teljesen megfordítva a meccs menetét.", 1),
        ("Holding (Visszahúzás)", "A holding az egyik leggyakrabban előforduló büntetés a pályán. Akkor ítélik, ha egy játékos szabálytalanul, a testével vagy a mezénél fogva megragadja vagy visszahúzza az ellenfelét. Ha a támadók szabálytalankodnak, 10 yardos büntetést kapnak, ami nagyon megnehezíti a támadás folytatását. Ha a védők követik el, az 5 yardos büntetés mellett a támadók automatikusan első kísérletet is kapnak.", 1),
        ("Intentional Grounding", "Ez egy súlyos, 10 yardos büntetés a támadók ellen, ami egy kísérlet elvesztésével is jár. Akkor ítélik, ha az irányító, hogy elkerüljön egy sack-et (földrevitelt), szándékosan olyan területre dobja a labdát, ahol nincs reális esélye egy csapattársnak sem elkapni azt. A szabály célja, hogy megakadályozza az irányítókat abban, hogy sportszerűtlenül szabaduljanak meg a labdától nyomás alatt. Ha a saját célterületén belül követik el, az safety-t eredményez.", 1),
        ("Kezdőrúgás (Kickoff)", "A félidők elején, valamint minden pontszerzés (touchdown vagy field goal) után egy speciális rúgással hozzák játékba a labdát. A rúgó csapat mélyen a saját térfeléről rúgja el a labdát a lehető legmesszebbre. Az ellenfél csapatának 'visszahordó' (returner) játékosa elkapja azt, és megpróbál minél több yardot előrehaladni vele, amíg a rúgó csapat játékosai le nem szerelik. A visszahordás helye határozza meg a következő támadássorozat kiindulópontját.", 1),
        ("Offside (Les)", "A les egy 5 yardos büntetés a védelem ellen. A játék megkezdése előtt a labda vonala egy képzeletbeli 'semleges zónát' hoz létre a támadó- és a védőfal között. Ha egy védőjátékos a labda játékba hozatala (snap) előtt belép ebbe a zónába vagy átlépi azt, 'offside'-ot követ el. Ezzel a védő igazságtalan előnyhöz jutna, ezért a szabálytalanságot a játék azonnali megállításával büntetik.", 1),
        ("Overtime (Hosszabbítás)", "Ha a rendes, négy negyedből álló játékidő végén döntetlen az állás, hosszabbítás következik a győztes eldöntésére. Az alapszakaszban az NFL egy módosított 'hirtelen halál' rendszert használ: az elsőként labdát kapó csapat ha touchdownt szerez, nyer. Ha csak mezőnygólt rúgnak, az ellenfél is kap egy esélyt a támadásra. Ha a hosszabbítás végén is döntetlen, a meccs döntetlennel ér véget (rájátszásban nincs döntetlen).", 1),
        ("Pass Interference (Passz akadályozás)", "Ez a szabály védi mind az elkapó, mind a védő jogát a labda elkapásához. Akkor ítélik, ha egy játékos azelőtt akadályozza az ellenfelét (löki, húzza, gáncsolja), hogy a labda odaérne, ezzel megakadályozva a tiszta elkapási kísérletet. A büntetés súlyos: a labda a szabálytalanság helyére kerül, ami akár több tíz yardos előnyt is jelenthet.", 1),
        ("Punt", "A punt egy stratégiai rúgás, amit a csapatok általában a negyedik kísérletnél alkalmaznak, ha úgy ítélik meg, hogy nincs reális esélyük első kísérletet vagy mezőnygólt szerezni. A punter a labdát a lehető legmesszebbre rúgja az ellenfél térfelére. A cél, hogy az ellenfelet a lehető legrosszabb mezőnypozícióból, a saját célterületükhöz a lehető legközelebbről kényszerítsék a támadás megkezdésére. Ez a pozíciós harc egyik legfontosabb eszköze.", 1),
        ("Roughing the Passer (Irányító durva támadása)", "Védői büntetés (15 yard és automatikus első kísérlet). Szigorúan védik az irányítókat; miután eldobta a labdát, nem lehet őt durván támadni vagy a földre vinni. Ez a szabály a sérülések megelőzését szolgálja a liga legértékesebb játékosainál. A védőknek kerülniük kell a sisakkal való ütközést és a lábak alacsony támadását.", 1),
        ("Safety", "A safety egy ritka, de nagyon értékes játéka a védelemnek, amely 2 pontot ér. Akkor ítélik, ha a védekező csapat a labdát birtokló támadójátékost annak saját célterületén (end zone) szereli. A 2 ponton felül a labdabirtoklás is a védekező csapathoz kerül, ami dupla előnyt jelent. Ez a játék teljesen megváltoztathatja egy mérkőzés dinamikáját.", 1),
        ("Touchdown (TD)", "A játék végső célja a touchdown szerzése, amely 6 pontot ér. Ezt akkor éri el a támadó csapat, ha a labdát bejuttatja az ellenfél célterületére (end zone), akár futva, akár egy elkapással. A touchdown után a pontszerző csapatnak lehetősége van további 1 vagy 2 pontot szerezni. A meccseket leginkább a szerzett touchdownok száma dönti el.", 1),
        ("Turnover on Downs", "Ha a támadócsapat a negyedik kísérleténél sem tudja elérni a szükséges távolságot (általában 10 yardot), és nem rúgnak puntot vagy mezőnygólt, akkor elveszítik a támadás jogát. A labda pontosan ott kerül az ellenfélhez, ahol az utolsó játék véget ért. Ez egy kockázatos döntés a támadók részéről, de sikeres végrehajtás esetén fenntarthatják a támadássorozatot.", 1),
        ("Two-Point Conversion", "Egy touchdown után a csapat dönthet úgy, hogy a biztosnak tűnő 1 pontos extra pont rúgása helyett megpróbálkozik egy kétpontos kísérlettel. Ehhez egyetlen játékból, a 2 yardos vonalról kell újra bejuttatniuk a labdát a célterületre. Ez egy magas kockázatú, de potenciálisan magasabb jutalommal járó játék, amit gyakran a meccs végén, kiélezett állásnál alkalmaznak.", 1),
        ("Unnecessary Roughness (Szükségtelen durvaság)", "Ez egy súlyos, 15 yardos személyi hiba büntetés, amit a játék szempontjából indokolatlan, sportszerűtlen vagy veszélyes fizikai kontaktusért ítélnek. Ide tartozik például a már földön lévő játékos megütése, a sisakkal való támadás, vagy a labdától távol történő durva lökés. A liga ezzel a szabállyal próbálja megóvni a játékosok testi épségét, és fenntartani a sportszerűség kereteit.", 1),

        # === Kifejezések (category_id = 2) ===
        ("Audible", "Az 'audible' az irányító egyik legfontosabb eszköze, amivel a védelem felállására reagálhat. Amikor a támadósor már felállt a kezdővonalhoz, de a játék még nem indult el, az irányítónak van lehetősége megváltoztatni az előre megbeszélt játékot. Ezt kódolt vezényszavak kiabálásával teszi meg, amivel új instrukciókat ad a csapattársainak. Egy sikeres 'audible' egy rossznak ígérkező játékot is nagy nyereséggé változtathat.", 2),
        ("Blitz", "A blitz egy magas kockázatú védelmi stratégia. A védelem a szokásos 3-4 helyett 5 vagy több játékost küld az irányító letámadására, hogy ne legyen ideje gondolkodni. Ha a blitz sikeres, az sack-et vagy egy elhamarkodott, rossz dobást eredményezhet. Azonban ha az irányító időben megszabadul a labdától, a védelem létszámhátrányba kerül, és nagy játékot engedhet az ellenfélnek.", 2),
        ("Drive", "A 'drive' egy teljes támadássorozatot jelöl. Attól a ponttól tart, hogy egy csapat megszerzi a labdabirtoklás jogát, egészen addig, amíg pontot nem szereznek (touchdown vagy field goal), el nem vesztik a labdát (turnover), vagy el nem rúgják azt (punt). Egy mérkőzés több ilyen drive-ból áll, a csapatok felváltva vezethetik támadásaikat. Egy hosszú, sok játékból álló, pontszerzéssel végződő drive fizikailag és mentálisan is megterhelő az ellenfél védelmére nézve.", 2),
        ("Gridiron", "A 'gridiron' az amerikai futballpálya beceneve. A szó a pálya jellegzetes, rácsos mintázatára utal, amit a yardokat jelölő párhuzamos vonalak hoznak létre. Ez a rácsháló segít a játékosoknak, a bíróknak és a nézőknek is a labda pontos pozíciójának és a megteendő távolságnak a meghatározásában. A kifejezés mára az amerikai futball sportág szinonimájává vált.", 2),
        ("Hail Mary", "A 'Hail Mary' egy utolsó, kétségbeesett próbálkozás a játék legvégén. Jellemzően akkor alkalmazzák, amikor egy csapatnak már nincs ideje másra, csak egyetlen játékra, és messze van a célterülettől. Az irányító a lehető legmagasabbra és legmesszebbre dobja a labdát az end zone felé, reménykedve, hogy a sok játékos közül az egyik csapattársa elkapja azt. Bár a siker esélye csekély, a történelem során több emlékezetes meccs dőlt el egy ilyen csodával határos módon.", 2),
        ("Icing the Kicker", "Ez egy pszichológiai hadviselés, amit az ellenfél edzője alkalmaz. Közvetlenül azelőtt, hogy a rúgójátékos (kicker) elvégezne egy fontos mezőnygólkísérletet, az edző időt kér. A cél az, hogy a rúgót kizökkentse a ritmusából, és több ideje legyen gondolkodni a rúgás tétjén, ezzel növelve a hibázás esélyét. A szabályok korlátozzák, hogy ezt hányszor lehet megtenni, de egy meccs végén gyakran látott taktika.", 2),
        ("Interception (INT)", "Az interception, vagy 'pick', a védelem egyik legértékesebb labdaszerzése. Akkor történik, amikor egy védőjátékos elkapja az ellenfél irányítójának passzát, még mielőtt az a földet érné. A labdabirtoklás joga azonnal a védekező csapathoz kerül, amelynek játékosa megpróbálhatja visszahordani a labdát a pontszerzés reményében. Ez a játék nemcsak megállít egy támadást, de azonnali támadási lehetőséget is teremt a labdát szerző csapatnak.", 2),
        ("Line of Scrimmage (Kezdővonal)", "A kezdővonal egy képzeletbeli, pálya szélességű vonal, amely a labda helyzetét jelöli a játék megkezdése előtt. A támadók és a védők e vonal két oldalán sorakoznak fel, a közöttük lévő terület a 'semleges zóna'. Egyetlen játékos sem léphet át ezen a vonalon a labda játékba hozatala (snap) előtt. A vonal helyzete minden játék után változik a labda előrehaladásának vagy hátra kerülésének megfelelően.", 2),
        ("Pick-Six", "A 'pick-six' a védelem által szerzett touchdown, a játék egyik leglátványosabb fordulata. A kifejezés a 'pick' (az interception, azaz elcsípett labda beceneve) és a 'six' (a touchdownért járó 6 pont) szavakból áll össze. Ez az a játék, amikor egy védő nemcsak elkapja az ellenfél passzát, de egyből vissza is hordja azt az ellenfél célterületére. Ez demoralizáló csapás a támadó csapatra, és hatalmas lendületet ad a védelemnek.", 2),
        ("Play Action Pass", "A play action egy cseles passzjáték, ami futásnak indul, hogy megtévessze a védelmet. Az irányító úgy tesz, mintha átadná a labdát a futójátékosnak, aki szintén eljátssza a labdacipelést. Eközben a futásra reagáló védők előre mozdulnak, üres területet hagyva maguk mögött. Az irányító ezt kihasználva passzol a védők mögé került elkapóknak. A hatékony futójáték elengedhetetlen a sikeres play actionhöz.", 2),
        ("Play Clock", "A 'play clock' egy visszaszámláló óra, ami biztosítja a játék folyamatosságát. A támadó csapatnak általában 40 másodperce van a labda játékba hozatalára az előző játék végétől számítva. Ez az óra jól látható a stadionban és a televíziós közvetítések során is. Ha lejár, mielőtt a játék elindulna, a támadó csapat 'Delay of Game' (játék késleltetése) büntetést kap, ami 5 yardos hátráltatást jelent.", 2),
        ("Pocket (Zseb)", "A zseb az a képzeletbeli védőburok, amit a támadófal játékosai (Offensive Line) alakítanak ki az irányító körül. Az irányítónak ezen a területen belül kell maradnia, amíg passzolási lehetőséget keres, mivel itt van a legnagyobb biztonságban a védőktől. Egy stabil, jól tartó zseb elengedhetetlen a sikeres passzjátékhoz. Ha a zseb 'összeomlik', az irányítónak futnia kell az életéért.", 2),
        ("Red Zone", "A Red Zone a pálya legfontosabb területe, az ellenfél célvonalától számított 20 yardos sáv. Amikor egy csapat bejut a Red Zone-ba, a pontszerzési esélyei drasztikusan megnőnek. A védelmek itt sokkal agressívabban játszanak a szűkebb terület miatt. A csapatok Red Zone-hatékonysága (hogy touchdownnal vagy csak mezőnygóllal fejezik-e be a támadást) kulcsfontosságú statisztika.", 2),
        ("Sack", "A 'sack' a védelem egyik leglátványosabb játéka. Akkor történik, ha a védelemnek sikerül a labdát birtokló irányítót a kezdővonal (line of scrimmage) mögött a földre vinnie (szerelnie). Ez nemcsak yardveszteséget okoz a támadóknak, hanem egy kísérletükbe (down) is kerül. Egy sack jelentősen visszavetheti a támadássorozatot, és mentálisan is megterhelő az irányító számára.", 2),
        ("Screen Pass", "A 'screen pass' egy rövid, cseles passzjáték, amely a védelem agresszivitását használja ki. A támadófal szándékosan átengedi a védőket, akik az irányítóra rohannak. Az irányító az utolsó pillanatban egy rövid passzt ejt a rohanó védők mögé, általában egy futójátékosnak. A futó előtt ekkor már a támadófalemberek blokkolják az utat, így nagy teret nyerhet. Ez a játék időzítést és pontos végrehajtást igényel.", 2),
        ("Special Teams", "A 'special teams' a csapat harmadik, specializált egysége a támadók (offense) és a védők (defense) mellett. Ők lépnek pályára a rúgójátékoknál: kezdőrúgásnál (kickoff), puntnál, mezőnygól- (field goal) és extra pont kísérleteknél. A tagjai gyakran a csapat fiatal, vagy cserejátékosai, de a rúgók (kicker) és a punterek magasan specializálódott profik. A special teams játéka gyakran észrevétlen, de egy-egy nagy visszahordás vagy blokkolt rúgás megváltoztathatja a meccs kimenetelét.", 2),
        ("Trenches (Árkok)", "Az 'árkok' a pálya azon területe, ahol a támadófal (Offensive Line) és a védőfal (Defensive Line) minden játék elején összecsap. Ez a fizikai küzdelem a játék alapja, bár a laikus nézők számára gyakran rejtve marad. Az a csapat, amelyik dominálni tud az 'árkokban', általában a futójátékot is uralja, és az irányítójának is több ideje van passzolni. A meccsek sorsa gyakran itt, a láthatatlan háborúban dől el.", 2),
        ("Turnover (Labdavesztés)", "A 'turnover' az a helyzet, amikor a támadó csapat akaratán kívül elveszíti a labdát, és az az ellenfélhez kerül. Két fő formája van: a 'fumble', amikor a játékos elejti a labdát, és az 'interception', amikor a passzát az ellenfél kapja el. A turnoverök a legköltségesebb hibák közé tartoznak, mert nemcsak a saját támadási lehetőséget szüntetik meg, de azonnali támadási jogot adnak az ellenfélnek, gyakran kedvező mezőnypozícióból.", 2),
        
        # === Játékosok (category_id = 3) ===
        ("Center (C)", "A Center a támadófal 'kapitánya', a sor közepén helyezkedik el. Két kritikus feladata van: ő indítja a játékot a labda hátraadásával (snap), és ő felel a blokkolási sémák bemondásáért és irányításáért. A Centernek egyszerre kell erősnek lennie a védők feltartásához és intelligensnek a védelem felállásának gyors elemzéséhez. Az irányítóval való összhangja, a snap pontossága, elengedhetetlen a sikeres támadójátékhoz.", 3),
        ("Cornerback (CB)", "A cornerback (CB) a védelem egyik legatletikusabb és leggyorsabb játékosa. Elsődleges feladata, hogy az ellenfél elkapóit (Wide Receiver) kövesse, és megakadályozza őket a passzok elkapásában. Ezt 'emberfogásnak' (man coverage) vagy zónavédekezésnek (zone coverage) részeként is végezheti. A jó cornerbackek nemcsak a passzokat ütik le, hanem labdát is szereznek (interception). Ez a pozíció óriási sebességet és gyors irányváltási képességet igényel.", 3),
        ("Defensive End (DE)", "A Defensive End (DE) a védőfal két szélén helyezkedik el. Ők a csapat elsődleges passzsiettetői, céljuk, hogy megkerüljék a támadófal szélén álló játékosokat (offensive tackle) és letámadják az irányítót (sack). Sebességük és erejük kombinációja elengedhetetlen. Emellett a futójátékoknál is fontos szerepük van, meg kell akadályozniuk, hogy a futók a pálya széle felé törjenek ki.", 3),
        ("Defensive Tackle (DT)", "A Defensive Tackle (DT) a védőfal belső, legerősebb és legtestesebb tagja. Az ő feladatuk a futójátékok megállítása a pálya közepén, azzal, hogy feltörik a támadófalat és lezárják a futófolyosókat. Emellett a passzjátékoknál az irányítóra gyakorolt belső nyomással segítik a passzsiettetőket. A DT-k a védelem 'erődítményei', akik a legkeményebb fizikai munkát végzik.", 3),
        ("Fullback (FB)", "A Fullback egy erősebb testalkatú futójátékos, akinek a modern futballban már nem a labdacipelés az elsődleges feladata. Sokkal inkább egyfajta ' faltörő kosként' funkcionál: a másik futójátékos (Running Back) előtt futva blokkolja az utat, utat nyitva a védők között. Emellett a rövid passzoknál is célpont lehet, és a passzvédekezésben is segít blokkolni. Ez egy önfeláldozó, a csapatsikert szolgáló pozíció.", 3),
        ("Guard (G)", "A Guard (G) a támadófal belső embere, a Center és a Tackle között helyezkedik el mindkét oldalon. Elsődleges feladata a passzjátékoknál az irányító előtti 'zseb' fenntartása a belső védőkkel szemben. Futójátékoknál gyakran 'húznak' (pulling), azaz kimozdulnak a helyükről, hogy a sor egy másik pontján vezessék fel a blokkolást a futó számára. Erő és mozgékonyság egyaránt szükséges ehhez a pozícióhoz.", 3),
        ("Kicker (K) - Rúgó", "A rúgó egy magasan specializálódott játékos, aki a speciális csapategység (Special Teams) tagja. Kizárólagos feladata a mezőnygólok (field goal) és az extra pontok elvégzése. Bár egy meccsen keveset van pályán, az ő teljesítménye gyakran döntő fontosságú, különösen a szoros mérkőzések végén. A rúgóknak rendkívül erős lábbal és mentális erővel kell rendelkezniük, hogy a hatalmas nyomás alatt is pontosak maradjanak.", 3),
        ("Linebacker (LB)", "A Linebacker (LB) a védelem 'svájci bicskája', a legsokoldalúbb védőjátékos. A védőfal mögött helyezkednek el, és egyszerre kell képesnek lenniük a futás megállítására, a passzsiettetésre (blitz), és a rövid-középtávú passzok levédekezésére. Ők a védelem vezérei, akik gyakran a legtöbb szerelést hajtják végre a meccsen. Pozíciójuk megköveteli az erőt, a sebességet és a magas szintű játékintelligenciát.", 3),
        ("Long Snapper (LS)", "A Long Snapper (LS) a speciális csapategység egy szinte láthatatlan, de nélkülözhetetlen hőse. Kizárólagos feladata, hogy a puntoknál és a field goal kísérleteknél a labdát nagy távolságra (7-15 yard) és tökéletes pontossággal adja hátra a punternek vagy a labdát tartó játékosnak. Munkája rendkívüli precizitást igényel, mivel egy rossz snap az egész játékot tönkreteheti. Egy csapat sikere gyakran egy megbízható Long Snapperen is múlik.", 3),
        ("Offensive Tackle (OT)", "Az Offensive Tackle (OT) a támadófal két szélén elhelyezkedő játékos. Ők a csapat legfontosabb blokkolói, különösen a passzjátékoknál. A jobbkezes irányító bal oldali tackle-je (Left Tackle) a legértékesebb, mert ő védi az irányító 'holtterét' a láthatatlanul érkező védőktől. A tackle-öknek egyszerre kell nagynak és erősnek lenniük a védők feltartóztatásához, valamint gyors lábúnak és mozgékonynak a passzsiettetők semlegesítéséhez.", 3),
        ("Punter (P)", "A punter a speciális csapategység tagja, aki a labda elrúgásáért felel negyedik kísérletnél. Célja, hogy a labdát a lehető legmagasabbra és legmesszebbre rúgja, úgy, hogy az ellenfél a lehető legmesszebb legyen kénytelen kezdeni a támadását. Egy jó punter képes a labdát pörgetni, és a pálya egy adott pontjára, például az oldalvonal mellé vagy a célterület közelébe rúgni. A mezőnypozíciós csatában a punter kulcsfontosságú fegyver.", 3),
        ("Quarterback (QB) - Irányító", "Az irányító a csapat agya és vezére a pályán, minden támadójáték az ő kezéből indul. Feladata, hogy az edzői stáb által meghatározott játékot végrehajtsa, olvassa a védelmet, és döntsön passz, futás vagy a labda átadása mellett. Nemcsak fizikai (erős kar, pontosság), de mentális képességei (játékolvasás, hidegvér) is meghatározóak. Ő a csapat legfontosabb és általában legismertebb játékosa.", 3),
        ("Running Back (RB) - Futójátékos", "A futójátékos egy robbanékony és erős atléta, akinek fő feladata, hogy a labdát cipelve a földön szerezzen teret. Át kell törnie a védők vonalán, ki kell használnia a blokkok által nyitott réseket, és el kell kerülnie a szereléseket. Emellett a passzjátékban is részt vesz, mint blokkoló vagy mint a rövid passzok célpontja. Egy jó futójátékos leveszi a terhet az irányító válláról, és egyensúlyt teremt a támadójátékban.", 3),
        ("Safety (S)", "A Safety (S) a védelem 'utolsó bástyája', a legtávolabb helyezkedik el a kezdővonaltól. Két fő típusa van: a Free Safety (FS), aki a pálya közepét védi a mély passzok ellen, és a Strong Safety (SS), aki gyakran közelebb játszik a vonalhoz és segít a futás elleni védekezésben. A Safetyk feladata, hogy megakadályozzák a nagy, pontszerző játékokat, és besegítsenek a cornerbackeknek. Ők a védelem biztonsági hálója.", 3),
        ("Tight End (TE)", "A Tight End (TE) egy hibrid pozíció a támadósorban, amely ötvözi az elkapók és a támadófalemberek képességeit. Felállásuk szerint a támadófal szélén helyezkednek el. Képesnek kell lenniük blokkolni a futójátékoknál, mint egy hatodik falember, ugyanakkor elég gyorsnak és ügyesnek kell lenniük ahhoz is, hogy passzútvonalakat fussanak és elkapják a labdát. Sokoldalúságuk miatt a modern támadósorok egyik legértékesebb fegyverévé váltak.", 3),
        ("Wide Receiver (WR) - Elkapó", "Az elkapók a támadósor leggyorsabb és legügyesebb kezű játékosai. Feladatuk, hogy az előre megtervezett útvonalakon fussanak, tisztára játsszák magukat a őket őrző védőktől (cornerbackek), és elkapják az irányító által dobott passzokat. Sebességük és elkapási képességük kulcsfontosságú a nagy, látványos játékokhoz. Gyakran ők szerzik a legtöbb touchdownt, és a támadójáték leglátványosabb elemeit produkálják.", 3),
        
        # === Csapatok (AFC - category_id = 4) - FRISSÍTVE A FELHASZNÁLÓ ÁLTAL ===
        ("Baltimore Ravens", "A franchise történelme során két Super Bowlt nyert, az elsőt a 2000-es szezonban egy történelmileg domináns védelemmel. A 2025-ös szezonban a kétszeres MVP Lamar Jackson és a veterán futó, Derrick Henry köré épülnek, miközben a másodvédelem megerősítésére fókuszálnak. Érdekesség, hogy a 'Ravens' (Hollók) nevet a szurkolók választották Edgar Allan Poe híres költeménye tiszteletére, aki Baltimore-ban élt. A csapatot egyértelműen a fizikai dominancia, a kemény futójáték és a elsöprő védelem jellemzi, ami egyfajta ellenáramlat a passzorientált AFC-ben.", 4),
        ("Buffalo Bills", "A csapat a 90-es években Marv Levy vezetésével zsinórban négy Super Bowl-on is részt vett, de mindet elvesztette. Jelenleg a csapat egy stratégiai átalakuláson megy keresztül, ahol a sztár elkapó Stefon Diggs elcserélése után az elit irányító Josh Allen köré építenek egy fiatalabb támadósort. A csapat kabala-dala az Isley Brothers 'Shout' című slágere, amely minden hazai pontszerzés után felcsendül a stadionban. A csapatot leginkább a 'Bills Mafia' néven ismert, rendkívül szenvedélyes és hűséges szurkolótábora jellemzi, akik híresek a meccs előtti hagyományaikról.", 4),
        ("Cincinnati Bengals", "A legendás edző, Paul Brown által alapított csapat háromszor is szerepelt Super Bowl-on, de mindhármat elvesztette. A 2025-ös kilátásaik attól függnek, hogy a védelem képes-e feljavulni és támogatni Joe Burrow elit passzjátékát. A csapatot az 1981-ben bevezetett, ikonikus tigriscsíkos sisakjuk teszi azonnal felismerhetővé. Leginkább egy modern 'üvegágyúként' jellemezhetők: egy elit támadósorral rendelkeznek, amelyet egy következetesen alulteljesítő védelem hátráltat.", 4),
        ("Cleveland Browns", "A múltban a profi futball korai dinasztiája voltak, utolsó bajnoki címüket 1964-ben a legendás Jim Brown vezetésével szerezték. A 2025-ös szezon kilátásai komorak, mivel hatalmas a bizonytalanság az irányító poszton, bár a Myles Garrett vezette védelem továbbra is a csapat erőssége. A Browns egyike annak a négy csapatnak, amely soha nem szerepelt Super Bowl-on. Jelenlegi helyzetüket az a teher határozza meg, hogy a Deshaun Watsonnak adott hatalmas, garantált szerződés miatt a csapat a középszerűség csapdájába esett.", 4),
        ("Denver Broncos", "A franchise-t leginkább a legendás irányító, John Elway határozza meg, aki öt Super Bowlba vezette a csapatot, és karrierje végén kettőt meg is nyert. A 2024-es biztató szezon után 2025-ben a csapat a fiatal irányító, Bo Nix és a vezetőedző, Sean Payton párosára épít, egy továbbra is erős védelemmel kiegészülve. A csapat otthona, az 1610 méteres tengerszint feletti magasságban fekvő stadion, egyedülálló előnyt biztosít számukra. Jelenlegi helyzetük a tökéletes edző-irányító összhang erejét bizonyítja, amely a vártnál sokkal gyorsabban gyorsította fel az újjáépítést.", 4),
        ("Houston Texans", "Az NFL legfiatalabb franchise-aként a legsikeresebb éveik a 2010-es években voltak, amikor hat divízió címet nyertek. Jelenleg egy feltörekvő csapatnak számítanak, amely a szenzációs fiatal irányító, C.J. Stroud és a védelem-központú vezetőedző, DeMeco Ryans köré épül. Érdekesség, hogy a Texans az egyetlen olyan NFL-csapat, amely soha nem játszott konferenciadöntőben. Identitásuk DeMeco Ryans alatt formálódik egy kemény, fegyelmezett, védekező csapattá, amelyet egy robbanékony passzjáték egészít ki.", 4),
        ("Indianapolis Colts", "A franchise történetének csúcspontja az 1958-as, 'Minden idők legjobb meccseként' emlegetett bajnoki döntő, valamint a Peyton Manning vezetésével megnyert Super Bowl XLI. A 2025-ös szezonjuk legfőbb kérdése az irányító poszt, ahol egy nyílt verseny várható a tapasztalatlan, de atletikus Anthony Richardson és a veterán Daniel Jones között. A csapat 1984-ben az éj leple alatt költözött Baltimore-ból Indianapolisba, hogy elkerülje a város jogi lépéseit. A Colts identitása történelmileg az elit irányítójátékra épül, Johnny Unitastól Peyton Manningig, és jelenleg is ezt a hagyományt próbálják folytatni.", 4),
        ("Jacksonville Jaguars", "A franchise meglepően sikeresen indult, már a második szezonjában (1996) eljutott az AFC Konferenciadöntőig, de azóta nagyrészt sikertelen. A 2025-ös szezon egy új korszak kezdete új edzői stábbal, a siker pedig Trevor Lawrence irányító egészségén és a nagy kockázatot jelentő újonc, Travis Hunter teljesítményén múlik. Az 1996-os rájátszásban az NFL történetének egyik legnagyobb meglepetését okozva győzték le a toronymagas esélyes Denver Broncost. Jelenlegi identitásukat a kétségbeesett lépés határozza meg, hogy egy transzcendens tehetséget (Travis Hunter) keressenek az évekig tartó középszerűség után.", 4),
        ("Kansas City Chiefs", "A csapat az AFL történetének legsikeresebb franchise-a volt, és megnyerte a Super Bowl IV-t, de ezt követően 50 évig nem nyert bajnoki címet. Jelenleg ők az NFL uralkodó dinasztiája, öt év alatt három Super Bowlt nyertek Patrick Mahomes és Andy Reid vezetésével. Érdekesség, hogy az alapító Lamar Hunt nevéhez fűződik a 'Super Bowl' elnevezés, amelyet gyermekei 'Super Ball' játéka ihletett. A csapatot a Mahomes-Reid páros kreatív és robbanékony támadójátéka határozza meg, amely képes kompenzálni a keret más területein lévő gyengeségeket is.", 4),
        ("Las Vegas Raiders", "A vándorló történelmű franchise három Super Bowlt nyert, identitását pedig a legendás tulajdonos, Al Davis 'Just win, baby' mottója és lázadó imázsa formálta. Jelenleg a csapat átalakulóban van, a 2025-ös szezont a tapasztalt Pete Carroll vezetésével és egy teljesen megújult támadósorral kezdik meg. A csapat eredetileg javasolt neve 1960-ban 'Oakland Señors' volt, de a széles körű gúnyolódás után Raiders-re változtatták. A franchise-t a 'Raider Nation', a sportvilág egyik legszenvedélyesebb és legfelismerhetőbb, ezüst-fekete színekről ismert szurkolótábora jellemzi.", 4),
        ("Los Angeles Chargers", "Történelmüket a 70-es és 80-as évek forradalmi, passz-központú 'Air Coryell' támadórendszere, valamint egy 1963-as AFL-bajnoki cím fémjelzi. A 2025-ös szezont az új vezetőedző, Jim Harbaugh irányítja, akitől egy keményebb, fizikálisabb identitás meghonosítását várják Justin Herbert sztárirányító mellé. A Chargers az egyetlen csapat, amely 0-4-es szezonkezdet után is bejutott a rájátszásba (1992). Harbaugh leigazolása egy tudatos kísérlet a franchise részéről, hogy megszabaduljon a 'puha', alulteljesítő hírnevétől.", 4),
        ("Miami Dolphins", "Történelmük csúcspontját az 1972-es szezon jelenti, amikor Don Shula vezetésével a liga történetében egyedülálló módon veretlenül nyerték meg a Super Bowlt. Mike McDaniel vezetőedző irányítása alatt a csapat a nagynevű igazolások helyett a támadó- és védőfal megerősítésére fókuszál, hogy egy ellenállóbb keretet építsen. A csapat nevét egy szurkolói pályázat útján választották ki, a nyertes pedig élethosszig tartó bérletet kapott a hazai meccsekre. A csapatot leginkább a Mike McDaniel által meghonosított rendkívül gyors és kreatív, mozgásra épülő támadójáték, valamint ikonikus türkiz és narancs színeik jellemzik.", 4),
        ("New England Patriots", "A franchise történelmét a Bill Belichick és Tom Brady nevével fémjelzett dinasztia határozta meg, amely 2001 és 2018 között hat Super Bowl-győzelmet hozott. Jelenleg a csapat teljes újjáépítés alatt áll, Mike Vrabel új vezetőedző vezetésével és a fiatal irányító, Drake Maye köré épített támadósorral. Érdekesség, hogy a csapatot 1971-ben majdnem 'Bay State Patriots'-nak nevezték át, de az ötletet elvetették, mert a rövidítése 'B.S. Patriots' lett volna. A csapatot a Bill Belichick által meghonosított 'The Patriot Way' jellemzi, amely a fegyelemre, az elszámoltathatóságra és a csapatszellemet előtérbe helyező filozófiára épül.", 4),
        ("New York Jets", "A franchise meghatározó pillanata az 1969-es Super Bowl III győzelem volt, amikor Joe Namath irányításával hatalmas meglepetésre legyőzték az esélyesebb Baltimore Colts csapatát. A csapat egy teljes újrakezdés előtt áll, miután az Aaron Rodgers-kísérlet kudarca után új vezetőedző, Aaron Glenn irányításával egy védelem- és futás-központúbb identitást építenek. A csapat nevét onnan kapta, hogy 1963-as új otthonuk, a Shea Stadion a New York-i LaGuardia repülőtér közelében helyezkedett el. A csapatot leginkább a 'Same Old Jets' kifejezéssel leírt, régóta tartó sikertelenség és a szurkolók krónikus csalódottsága jellemzi, miközben történelmileg egy kemény, védekező identitásra törekszenek.", 4),
        ("Pittsburgh Steelers", "Az 1970-es években a sporttörténelem egyik legnagyobb dinasztiáját építették fel, hat év alatt négy Super Bowlt nyerve. A 2025-ös szezonban egy rövid távú, nagy tétekkel járó stratégiát követnek, leigazolva a veterán Aaron Rodgers-t és Jalen Ramsey-t egy azonnali bajnoki cím reményében. A Steelers az egyetlen NFL-csapat, amelynek logója csak a sisak egyik oldalán található. A franchise-t a stabilitás (1969 óta mindössze három vezetőedző) és a kemény, fizikális védelemre épülő identitás jellemzi.", 4),
        
        # === Csapatok (NFC - category_id = 5) - FRISSÍTVE A FELHASZNÁLÓ ÁLTAL ===
        ("Arizona Cardinals", "Az Egyesült Államok legrégebbi, folyamatosan működő profi futball franchise-aként a csapat utolsó NFL-bajnoki címét 1947-ben nyerte. A 2025-ös szezon kulcsfontosságú lesz Kyler Murray irányító és Jonathan Gannon vezetőedző számára, akikre nagy nyomás nehezedik, hogy bizonyítsanak. Egy 1929-es meccsen a legendás futójuk, Ernie Nevers 40 pontot szerzett, ami máig fennálló NFL-rekord. A csapatot a hosszú, de sikerekben szegény történelem és a folyamatos újjáépítés állapota jellemzi.", 5),
        ("Atlanta Falcons", "A franchise történelme során kétszer jutott Super Bowl-ba, a leghíresebb a 28-3-as vezetésről elvesztett döntő a Patriots ellen. A 2025-ös szezon a fiatal újonc irányító, Michael Penix Jr. körüli építkezésről szól, akit tehetséges támadók sora vesz körül. Az 1977-es 'Grits Blitz' néven elhíresült védelmük máig NFL-rekordot tart az egy szezonban engedett legkevesebb ponttal. A csapatot egy klasszikus 'fiatal irányító, kész keret' helyzet jellemzi, ahol a támadóoldali tehetséghalmozásnak kell kompenzálnia a védelem hiányosságait.", 5),
        ("Carolina Panthers", "Történelmük csúcsa a 2015-ös szezon volt, amikor Cam Newton MVP-játékával 15-1-es mérleget értek el és bejutottak a Super Bowl 50-be. Jelenleg egyértelműen egy hosszú újjáépítési folyamatban vannak, amelynek középpontjában a másodéves irányító, Bryce Young fejlesztése áll. A csapat logója lazán Észak- és Dél-Karolina körvonalait formázza. Identitásukat a tulajdonos, David Tepper alatti instabilitás és a háttérben húzódó elégedetlenség jellemzi, ami kihívást jelent az új edzői stábnak.", 5),
        ("Chicago Bears", "A liga alapító tagjaként történelmüket a 'Monsters of the Midway' becenévvel illetett domináns védelmek és a legendás 1985-ös Super Bowl-győztes csapat fémjelzi. A 2025-ös szezon egy újrakezdést jelent, amelynek fókuszában a 2024-es 1/1-es választott, Caleb Williams irányító fejlesztése áll egy új, támadóguru hírében álló vezetőedzővel. A csapatot azért nevezték el 'Bears'-nek (Medvék), mert az alapító szerint a futballisták nagyobbak, mint a város baseballcsapatának, a 'Cubs'-nak (Kölykök) a játékosai. A franchise a 2025-ös szezonra egy drámai, 180 fokos fordulatot hajtott végre, évtizedekig tartó védelem-központúság után egy támadás-első identitásra váltva.", 5),
        ("Dallas Cowboys", "A 70-es évek óta 'Amerika Csapataként' ismert franchise a 90-es években épített dinasztiát, négy év alatt három Super Bowlt nyerve. A 2025-ös szezon egy átmeneti év új vezetőedzővel, miközben a csapat a rájátszásért harcolhat, de komoly kérdések övezik a kulcsjátékosok helyzetét. A Forbes szerint a Cowboys a világ legértékesebb sportfranchise-a, 2023-ban 9 milliárd dollárra becsülték az értékét. A csapat identitását az 'Amerika Csapata' becenév, a hatalmas nemzeti rajongótábor és az ikonikus kék csillag logó határozza meg.", 5),
        ("Detroit Lions", "A korai sikerek és az 50-es években nyert három bajnoki cím után egy hosszú, sikertelen időszak következett, a Super Bowl-korszakban soha nem jutottak el a döntőig. Egy történelmi 2024-es alapszakasz után 2025-ben az a legnagyobb kihívás számukra, hogy pótolják a távozó sikeredzőiket és bizonyítsák, hogy a Dan Campbell által felépített kultúra fenntartható. A Lions egyik legrégebbi hagyománya a hálaadásnapi mérkőzés, amelyet 1934 óta szinte minden évben megrendeznek. Jelenlegi helyzetük egy kritikus teszt, amely megmutatja, hogy a siker a kultúrán vagy a távozó edzők zsenialitásán múlott-e.", 5),
        ("Green Bay Packers", "A Packers nyerte a legtöbb bajnoki címet (13) az NFL történetében, beleértve az első két Super Bowlt a legendás Vince Lombardi vezetésével. A 2025-ös szezon a Jordan Love irányító körüli építkezés folytatásáról szól, akit a franchise jövőjének tekintenek. Érdekesség, hogy a franchise egyedülálló módon nonprofit, közösségi tulajdonban van, nem pedig egyetlen tulajdonos birtokolja. A Packers identitását a 'kisvárosi csapatok' utolsó képviselőjeként, a történelmi Lambeau Field stadion és a közösségi tulajdonlás egyedi modellje határozza meg.", 5),
        ("Los Angeles Rams", "Történelmüket olyan ikonikus egységek fémjelzik, mint a 60-as évek 'Fearsome Foursome' védőfala és a 90-es évek végének 'The Greatest Show on Turf' támadósora. A 2025-ös szezonban a csapat a védelem újjáépítésére koncentrál a legendás Aaron Donald visszavonulása után, miközben a Matthew Stafford vezette támadósor továbbra is a liga elitjébe tartozik. Érdekesség, hogy ők az egyetlen NFL-franchise, amely három különböző városban (Cleveland, Los Angeles, St. Louis) is bajnoki címet nyert. A csapat identitását a csillogás és az innováció jellemzi, a 40-es évek úttörő sisakdíszítésétől kezdve a modern kor robbanékony támadójátékáig.", 5),
        ("Minnesota Vikings", "Történelmüket a 'majdnem sikerült' történetek jellemzik: egy NFL-bajnoki címet nyertek, de mind a négy Super Bowl-szereplésüket elvesztették. Egy váratlanul sikeres 2024-es szezon után 2025-re egy teljesen tapasztalatlan, első körös újonc irányítóra, J.J. McCarthyra bízzák a csapatot. A Vikings rendelkezik a legmagasabb győzelmi aránnyal azon NFL-csapatok között, amelyek soha nem nyertek Super Bowlt. A csapat jelenlegi helyzete egy érdekes kísérlet, hogy a sikeres rendszerük egy bizonyítatlan irányítóval is működőképes-e.", 5),
        ("New Orleans Saints", "A csapat sorsa a Katrina-hurrikán után fordult meg, ami a 2009-es szezonban a Drew Brees vezette Super Bowl-győzelemben csúcsosodott ki. Egy katasztrofális 2024-es idény után 2025 egy teljes újjáépítés kezdete új vezetőedzővel és bizonytalan irányító helyzettel. Érdekesség, hogy 1970-ben a lábujjak nélkül született rúgó, Tom Dempsey, egy akkor NFL-rekordot jelentő, 63 yardos mezőnygólt rúgott. A csapat egy nehéz átmeneti időszakban van a sikeres Brees/Payton-éra után, identitásuk pedig a szenvedélyes 'Who Dat Nation' szurkolótáborra épül.", 5),
        ("New York Giants", "Az NFL egyik legrégebbi franchise-aként négy Super Bowlt nyertek, köztük egy emlékezetes győzelmet a 2008-as döntőben a veretlen New England Patriots ellen. Egy katasztrofális 2024-es szezon után a 2025-ös év egyfajta utolsó esély a jelenlegi vezetőségnek, miközben veterán irányítókkal próbálnak sikert elérni, és egy újoncot fejlesztenek a jövőre. A csapatot jogilag ma is 'New York Football Giants'-nek hívják, hogy megkülönböztessék magukat az egykori, azonos nevű baseball csapattól. A Giants identitása a hosszú, gazdag történelemre és a kemény, védekező stílusú futballra épül.", 5),
        ("Philadelphia Eagles", "A csapat első Super Bowl-győzelmét a 2017-es szezonban aratta, majd a 2024-es szezonban Jalen Hurts vezetésével ismét diadalmaskodtak. Címvédőként lépnek pályára a 2025-ös szezonban, ahol a támadósoruk magja érintetlen maradt, de a védelemben jelentős veszteségek érték őket. Az Eagles az egyetlen csapat, amely két különböző franchise ellen is bosszút állt egy Super Bowl vereségért (Patriots, Chiefs). A csapatot egy agresszív, a falak mentén domináló játékstílus és a 'Tush Push' nevű, szinte megállíthatatlan rövid yardos játéka jellemzi.", 5),
        ("San Francisco 49ers", "A 80-as években a liga domináns csapata voltak, a Bill Walsh vezetőedző és Joe Montana irányító nevével fémjelzett dinasztia négy Super Bowlt nyert. Egy katasztrofális, sérülésekkel teli 2024-es szezon után 2025-ben a visszatérésben és a kulcsjátékosok egészségében bíznak. A 80-as évek sikercsapatának döntőjét eldöntő passzát Joe Montana és Dwight Clark között 'The Catch'-ként emlegetik, ami az NFL történetének egyik legikonikusabb játéka. A csapat identitását a Bill Walsh által bevezetett, rövid, precíz passzokra épülő 'West Coast Offense' határozza meg.", 5),
        ("Seattle Seahawks", "A csapat történelmének legfényesebb korszaka a 2010-es évekre tehető, amikor a 'Legion of Boom' néven ismert domináns védelemmel megnyerték a Super Bowl XLVIII-at. A 2025-ös szezon új korszakot jelent, miután Pete Carroll távozott, és az új vezetőedző, Mike Macdonald egyfajta újjáépítésbe kezd a fiatal kerettel. A Seahawks az egyetlen csapat, amely játszott mind az AFC, mind az NFC konferenciadöntőjében. A csapat egy identitásváltás közepén van, ahol a laza, játékos-központú kultúrát egy fegyelmezettebb, séma-központúbb megközelítés váltja fel.", 5),
        ("Tampa Bay Buccaneers", "A franchise első bajnoki címét egy domináns védelemmel nyerte 2002-ben, a másodikat pedig 18 évvel később, Tom Brady irányításával. A 2025-ös szezonban a rájátszás esélyesei közé tartoznak Baker Mayfield irányítóval, aki stabilizálta a posztot a Brady utáni korszakban. A Buccaneers a Baltimore Ravens mellett az egyetlen olyan csapat, amely több Super Bowl-on is veretlen maradt. Identitásukat a hullámzó teljesítmény jellemzi: a történelmi mélypontoktól (mint a 26 meccses vereségsorozat) a bajnoki magasságokig (két Super Bowl-cím).", 5),
        ("Washington Commanders", "A franchise második aranykorát Joe Gibbs edző nevéhez fűződik, aki három Super Bowlt nyert három különböző irányítóval. Egy meglepő 2024-es sikerszezon után 2025-re a Super Bowl esélyesek közé léptek elő, a fordulat motorja pedig a szenzációs újonc szezont produkáló Jayden Daniels irányító volt. A Commanders volt az első NFL-csapat, amelynek saját indulója volt. A csapat újjászületése azt példázza, hogyan képes egy professzionális vezetőség és egy tehetséges fiatal irányító kombinációja gyorsan átformálni egy vergődő franchise-t egy bajnokesélyessé.", 5)
    ]
    cursor.executemany('INSERT INTO entries (term, description, category_id) VALUES (?, ?, ?)', entries_to_add)
    print(f"{len(entries_to_add)} bejegyzés sikeresen hozzáadva az adatbázishoz.")

except sqlite3.Error as e:
    print(f"Hiba történt: {e}")

# Változtatások mentése és kapcsolat bezárása
conn.commit()
conn.close()

print("Az adatbázis újraépítése és feltöltése befejeződött.")