# EZ A TELJES ÉS VÉGLEGES VERZIÓ, MINDEN BEJEGYZÉSSEL
import sqlite3
import os

DB_FILE = "nfl_akademia.db"

# Töröljük a régi adatbázis fájlt, ha létezik, hogy teljesen tiszta alapról induljunk
if os.path.exists(DB_FILE):
    os.remove(DB_FILE)
    print(f"A régi '{DB_FILE}' adatbázis sikeresen törölve.")

# Csatlakozás az új, üres adatbázishoz
conn = sqlite3.connect(DB_FILE)
cursor = conn.cursor()

# --- Táblák létrehozása ---
cursor.execute('''
    CREATE TABLE categories (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL UNIQUE
    )
''')
cursor.execute('''
    CREATE TABLE entries (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        term TEXT NOT NULL,
        description TEXT NOT NULL,
        category_id INTEGER,
        FOREIGN KEY (category_id) REFERENCES categories (id)
    )
''')
print("Adatbázis táblák sikeresen létrehozva.")

# --- Kategóriák és Bejegyzések Hozzáadása ---
try:
    # Kategóriák
    categories_to_add = [
        ("Szabályok",), 
        ("Kifejezések",),
        ("Játékosok",),
        ("Csapatok (AFC)",), 
        ("Csapatok (NFC)",)
    ]
    cursor.executemany('INSERT OR IGNORE INTO categories (name) VALUES (?)', categories_to_add)
    print("Kategóriák hozzáadva.")

    # Bejegyzések (Teljes, Végleges Lista, Bővített Leírásokkal)
    entries_to_add = [
        # === Szabályok (category_id = 1) ===
        ("Challenge (Kihívás)", "Az edzőknek meccsenként kétszer van lehetőségük egy piros zászló bedobásával videóbírói visszajátszást kérni egy vitatott ítéletre. Ha a kihívás sikeres, az ítéletet megváltoztatják, és az edző megtarthatja a lehetőséget. Ha a kihívás sikertelen, az ítélet marad, és az edző elveszít egy időkérést. Ez egy stratégiai elem, amit a meccs kritikus pillanataiban használnak.", 1),
        ("Delay of Game (Játék késleltetése)", "A támadó csapatnak meghatározott ideje van (általában 40 másodperc) elindítani a következő játékot, amit a 'play clock' mér. Ha ez az óra lejár, mielőtt a játék elindulna, a csapat 5 yardos büntetést kap. Ez a szabály biztosítja a játék folyamatosságát és megakadályozza az időhúzást. A nagy vendég szurkolói hangzavar gyakran okoz ilyen büntetést, mert a támadók nem hallják egymást.", 1),
        ("Down (Kísérlet)", "A támadó csapatnak négy kísérlete (down) van arra, hogy a labdával legalább 10 yardot előrehaladjon. Minden egyes játék, ami a labda hátraadásával (snap) kezdődik, egy 'down'-nak számít. A TV-s közvetítéseken gyakran látni kiírásokat, mint '1st & 10', ami első kísérletet és 10 megteendő yardot jelent. Ez a rendszer adja a játék alapvető ritmusát és stratégiai mélységét.", 1),
        ("Extra Pont (PAT)", "Egy sikeres touchdown (6 pont) után a pontszerző csapatnak lehetősége van egy bónuszpontra. Az extra pont, vagy PAT (Point After Touchdown), egy rövid rúgás a kapura, ami 1 pontot ér. Ez régen szinte automatikus volt, de a távolság növelésével mára egy izgalmasabb, de még mindig nagy százalékban sikeres játékelem. A csapat dönthet úgy is, hogy inkább a kockázatosabb kétpontos kísérletet választja.", 1),
        ("False Start (Rossz rajt)", "Ez egy gyakori, 5 yardos büntetés, amit a támadócsapat ellen ítélnek. Akkor történik, ha egy támadójátékos (az irányítón kívül) a labda játékba hozatala (snap) előtt megmozdul. Ez a szabály megakadályozza, hogy a támadók igazságtalan előnyhöz jussanak a védőkkel szemben. Egyetlen rossz mozdulat is hátrányos helyzetbe hozhatja a támadókat.", 1),
        ("Field Goal (FG)", "A mezőnygól 3 pontot ér, és általában akkor próbálkozik vele egy csapat, ha a negyedik kísérletnél járnak, de túl messze vannak egy újabb első kísérlethez, viszont elég közel a kapuhoz. A rúgójátékosnak (kicker) a labdát a két függőleges kapufa és a keresztléc fölé kell rúgnia. A mezőnygólok, különösen a meccs végén, gyakran döntenek a győzelemről, így a rúgójátékosok idegei aranyat érnek.", 1),
        ("First Down (Első kísérlet)", "A 'first down' a támadósorozat motorja. Amikor a támadócsapat sikeresen megteszi a szükséges 10 (vagy több) yardot a rendelkezésére álló négy kísérleten belül, jutalmul egy teljesen új, négy kísérletből álló sorozatot kap. Ezzel a labdabirtoklás folytatódik, és a csapat tovább haladhat a célterület felé. A cél tehát mindig az, hogy a csapat folyamatosan 'first down'-okat érjen el, fenntartva a támadást.", 1),
        ("Fumble", "A 'fumble' egy élő labdavesztés, ami akkor történik, amikor a labdát cipelő játékos elejti azt, mielőtt a földet érné (szerelés után). A labda 'szabaddá' válik, és bármelyik csapat játékosa megszerezheti, aki először rávetődik. Ez a játék egyik legkaotikusabb és legizgalmasabb pillanata lehet, mivel egyetlen mozdulattal az ellenfélhez kerülhet a támadás joga, teljesen megfordítva a meccs menetét.", 1),
        ("Holding (Visszahúzás)", "A holding az egyik leggyakrabban előforduló büntetés a pályán. Akkor ítélik, ha egy játékos szabálytalanul, a testével vagy a mezénél fogva megragadja vagy visszahúzza az ellenfelét. Ha a támadók szabálytalankodnak, 10 yardos büntetést kapnak, ami nagyon megnehezíti a támadás folytatását. Ha a védők követik el, az 5 yardos büntetés mellett a támadók automatikusan első kísérletet is kapnak.", 1),
        ("Intentional Grounding", "Ez egy súlyos, 10 yardos büntetés a támadók ellen, ami egy kísérlet elvesztésével is jár. Akkor ítélik, ha az irányító, hogy elkerüljön egy sack-et (földrevitelt), szándékosan olyan területre dobja a labdát, ahol nincs reális esélye egy csapattársnak sem elkapni azt. A szabály célja, hogy megakadályozza az irányítókat abban, hogy sportszerűtlenül szabaduljanak meg a labdától nyomás alatt. Ha a saját célterületén belül követik el, az safety-t eredményez.", 1),
        ("Kezdőrúgás (Kickoff)", "A félidők elején, valamint minden pontszerzés (touchdown vagy field goal) után egy speciális rúgással hozzák játékba a labdát. A rúgó csapat mélyen a saját térfeléről rúgja el a labdát a lehető legmesszebbre. Az ellenfél csapatának 'visszahordó' (returner) játékosa elkapja azt, és megpróbál minél több yardot előrehaladni vele, amíg a rúgó csapat játékosai le nem szerelik. A visszahordás helye határozza meg a következő támadássorozat kiindulópontját.", 1),
        ("Offside (Les)", "A les egy 5 yardos büntetés a védelem ellen. A játék megkezdése előtt a labda vonala egy képzeletbeli 'semleges zónát' hoz létre a támadó- és a védőfal között. Ha egy védőjátékos a labda játékba hozatala (snap) előtt belép ebbe a zónába vagy átlépi azt, 'offside'-ot követ el. Ezzel a védő igazságtalan előnyhöz jutna, ezért a szabálytalanságot a játék azonnali megállításával büntetik.", 1),
        ("Overtime (Hosszabbítás)", "Ha a rendes, négy negyedből álló játékidő végén döntetlen az állás, hosszabbítás következik a győztes eldöntésére. Az alapszakaszban az NFL egy módosított 'hirtelen halál' rendszert használ: az elsőként labdát kapó csapat ha touchdownt szerez, nyer. Ha csak mezőnygólt rúgnak, az ellenfél is kap egy esélyt a támadásra. Ha a hosszabbítás végén is döntetlen, a meccs döntetlennel ér véget (rájátszásban nincs döntetlen).", 1),
        ("Pass Interference (Passz akadályozás)", "Ez a szabály védi mind az elkapó, mind a védő jogát a labda elkapásához. Akkor ítélik, ha egy játékos azelőtt akadályozza az ellenfelét (löki, húzza, gáncsolja), hogy a labda odaérne, ezzel megakadályozva a tiszta elkapási kísérletet. A büntetés súlyos: a labda a szabálytalanság helyére kerül, ami akár több tíz yardos előnyt is jelenthet.", 1),
        ("Punt", "A punt egy stratégiai rúgás, amit a csapatok általában a negyedik kísérletnél alkalmaznak, ha úgy ítélik meg, hogy nincs reális esélyük első kísérletet vagy mezőnygólt szerezni. A punter a labdát a lehető legmesszebbre rúgja az ellenfél térfelére. A cél, hogy az ellenfelet a lehető legrosszabb mezőnypozícióból, a saját célterületükhöz a lehető legközelebbről kényszerítsék a támadás megkezdésére. Ez a pozíciós harc egyik legfontosabb eszköze.", 1),
        ("Roughing the Passer (Irányító durva támadása)", "Védői büntetés (15 yard és automatikus első kísérlet). Szigorúan védik az irányítókat; miután eldobta a labdát, nem lehet őt durván támadni vagy a földre vinni. Ez a szabály a sérülések megelőzését szolgálja a liga legértékesebb játékosainál. A védőknek kerülniük kell a sisakkal való ütközést és a lábak alacsony támadását.", 1),
        ("Safety", "A safety egy ritka, de nagyon értékes játéka a védelemnek, amely 2 pontot ér. Akkor ítélik, ha a védekező csapat a labdát birtokló támadójátékost annak saját célterületén (end zone) szereli. A 2 ponton felül a labdabirtoklás is a védekező csapathoz kerül, ami dupla előnyt jelent. Ez a játék teljesen megváltoztathatja egy mérkőzés dinamikáját.", 1),
        ("Touchdown (TD)", "A játék végső célja a touchdown szerzése, amely 6 pontot ér. Ezt akkor éri el a támadó csapat, ha a labdát bejuttatja az ellenfél célterületére (end zone), akár futva, akár egy elkapással. A touchdown után a pontszerző csapatnak lehetősége van további 1 vagy 2 pontot szerezni. A meccseket leginkább a szerzett touchdownok száma dönti el.", 1),
        ("Turnover on Downs", "Ha a támadócsapat a negyedik kísérleténél sem tudja elérni a szükséges távolságot (általában 10 yardot), és nem rúgnak puntot vagy mezőnygólt, akkor elveszítik a támadás jogát. A labda pontosan ott kerül az ellenfélhez, ahol az utolsó játék véget ért. Ez egy kockázatos döntés a támadók részéről, de sikeres végrehajtás esetén fenntarthatják a támadássorozatot.", 1),
        ("Two-Point Conversion", "Egy touchdown után a csapat dönthet úgy, hogy a biztosnak tűnő 1 pontos extra pont rúgása helyett megpróbálkozik egy kétpontos kísérlettel. Ehhez egyetlen játékból, a 2 yardos vonalról kell újra bejuttatniuk a labdát a célterületre. Ez egy magas kockázatú, de potenciálisan magasabb jutalommal járó játék, amit gyakran a meccs végén, kiélezett állásnál alkalmaznak.", 1),
        ("Unnecessary Roughness (Szükségtelen durvaság)", "Ez egy súlyos, 15 yardos személyi hiba büntetés, amit a játék szempontjából indokolatlan, sportszerűtlen vagy veszélyes fizikai kontaktusért ítélnek. Ide tartozik például a már földön lévő játékos megütése, a sisakkal való támadás, vagy a labdától távol történő durva lökés. A liga ezzel a szabállyal próbálja megóvni a játékosok testi épségét, és fenntartani a sportszerűség kereteit.", 1),

        # === Kifejezések (category_id = 2) ===
        ("Audible", "Az 'audible' az irányító egyik legfontosabb eszköze, amivel a védelem felállására reagálhat. Amikor a támadósor már felállt a kezdővonalhoz, de a játék még nem indult el, az irányítónak van lehetősége megváltoztatni az előre megbeszélt játékot. Ezt kódolt vezényszavak kiabálásával teszi meg, amivel új instrukciókat ad a csapattársainak. Egy sikeres 'audible' egy rossznak ígérkező játékot is nagy nyereséggé változtathat.", 2),
        ("Blitz", "A blitz egy magas kockázatú védelmi stratégia. A védelem a szokásos 3-4 helyett 5 vagy több játékost küld az irányító letámadására, hogy ne legyen ideje gondolkodni. Ha a blitz sikeres, az sack-et vagy egy elhamarkodott, rossz dobást eredményezhet. Azonban ha az irányító időben megszabadul a labdától, a védelem létszámhátrányba kerül, és nagy játékot engedhet az ellenfélnek.", 2),
        ("Drive", "A 'drive' egy teljes támadássorozatot jelöl. Attól a ponttól tart, hogy egy csapat megszerzi a labdabirtoklás jogát, egészen addig, amíg pontot nem szereznek (touchdown vagy field goal), el nem vesztik a labdát (turnover), vagy el nem rúgják azt (punt). Egy mérkőzés több ilyen drive-ból áll, a csapatok felváltva vezethetik támadásaikat. Egy hosszú, sok játékból álló, pontszerzéssel végződő drive fizikailag és mentálisan is megterhelő az ellenfél védelmére nézve.", 2),
        ("Gridiron", "A 'gridiron' az amerikai futballpálya beceneve. A szó a pálya jellegzetes, rácsos mintázatára utal, amit a yardokat jelölő párhuzamos vonalak hoznak létre. Ez a rácsháló segít a játékosoknak, a bíróknak és a nézőknek is a labda pontos pozíciójának és a megteendő távolságnak a meghatározásában. A kifejezés mára az amerikai futball sportág szinonimájává vált.", 2),
        ("Hail Mary", "A 'Hail Mary' egy utolsó, kétségbeesett próbálkozás a játék legvégén. Jellemzően akkor alkalmazzák, amikor egy csapatnak már nincs ideje másra, csak egyetlen játékra, és messze van a célterülettől. Az irányító a lehető legmagasabbra és legmesszebbre dobja a labdát az end zone felé, reménykedve, hogy a sok játékos közül az egyik csapattársa elkapja azt. Bár a siker esélye csekély, a történelem során több emlékezetes meccs dőlt el egy ilyen csodával határos módon.", 2),
        ("Icing the Kicker", "Ez egy pszichológiai hadviselés, amit az ellenfél edzője alkalmaz. Közvetlenül azelőtt, hogy a rúgójátékos (kicker) elvégezne egy fontos mezőnygólkísérletet, az edző időt kér. A cél az, hogy a rúgót kizökkentse a ritmusából, és több ideje legyen gondolkodni a rúgás tétjén, ezzel növelve a hibázás esélyét. A szabályok korlátozzák, hogy ezt hányszor lehet megtenni, de egy meccs végén gyakran látott taktika.", 2),
        ("Interception (INT)", "Az interception, vagy 'pick', a védelem egyik legértékesebb labdaszerzése. Akkor történik, amikor egy védőjátékos elkapja az ellenfél irányítójának passzát, még mielőtt az a földet érné. A labdabirtoklás joga azonnal a védekező csapathoz kerül, amelynek játékosa megpróbálhatja visszahordani a labdát a pontszerzés reményében. Ez a játék nemcsak megállít egy támadást, de azonnali támadási lehetőséget is teremt a labdát szerző csapatnak.", 2),
        ("Line of Scrimmage (Kezdővonal)", "A kezdővonal egy képzeletbeli, pálya szélességű vonal, amely a labda helyzetét jelöli a játék megkezdése előtt. A támadók és a védők e vonal két oldalán sorakoznak fel, a közöttük lévő terület a 'semleges zóna'. Egyetlen játékos sem léphet át ezen a vonalon a labda játékba hozatala (snap) előtt. A vonal helyzete minden játék után változik a labda előrehaladásának vagy hátra kerülésének megfelelően.", 2),
        ("Pick-Six", "A 'pick-six' a védelem által szerzett touchdown, a játék egyik leglátványosabb fordulata. A kifejezés a 'pick' (az interception, azaz elcsípett labda beceneve) és a 'six' (a touchdownért járó 6 pont) szavakból áll össze. Ez az a játék, amikor egy védő nemcsak elkapja az ellenfél passzát, de egyből vissza is hordja azt az ellenfél célterületére. Ez demoralizáló csapás a támadó csapatra, és hatalmas lendületet ad a védelemnek.", 2),
        ("Play Action Pass", "A play action egy cseles passzjáték, ami futásnak indul, hogy megtévessze a védelmet. Az irányító úgy tesz, mintha átadná a labdát a futójátékosnak, aki szintén eljátssza a labdacipelést. Eközben a futásra reagáló védők előre mozdulnak, üres területet hagyva maguk mögött. Az irányító ezt kihasználva passzol a védők mögé került elkapóknak. A hatékony futójáték elengedhetetlen a sikeres play actionhöz.", 2),
        ("Play Clock", "A 'play clock' egy visszaszámláló óra, ami biztosítja a játék folyamatosságát. A támadó csapatnak általában 40 másodperce van a labda játékba hozatalára az előző játék végétől számítva. Ez az óra jól látható a stadionban és a televíziós közvetítések során is. Ha lejár, mielőtt a játék elindulna, a támadó csapat 'Delay of Game' (játék késleltetése) büntetést kap, ami 5 yardos hátráltatást jelent.", 2),
        ("Pocket (Zseb)", "A zseb az a képzeletbeli védőburok, amit a támadófal játékosai (Offensive Line) alakítanak ki az irányító körül. Az irányítónak ezen a területen belül kell maradnia, amíg passzolási lehetőséget keres, mivel itt van a legnagyobb biztonságban a védőktől. Egy stabil, jól tartó zseb elengedhetetlen a sikeres passzjátékhoz. Ha a zseb 'összeomlik', az irányítónak futnia kell az életéért.", 2),
        ("Red Zone", "A Red Zone a pálya legfontosabb területe, az ellenfél célvonalától számított 20 yardos sáv. Amikor egy csapat bejut a Red Zone-ba, a pontszerzési esélyei drasztikusan megnőnek. A védelmek itt sokkal agresszívabban játszanak a szűkebb terület miatt. A csapatok Red Zone-hatékonysága (hogy touchdownnal vagy csak mezőnygóllal fejezik-e be a támadást) kulcsfontosságú statisztika.", 2),
        ("Sack", "A 'sack' a védelem egyik leglátványosabb játéka. Akkor történik, ha a védelemnek sikerül a labdát birtokló irányítót a kezdővonal (line of scrimmage) mögött a földre vinnie (szerelnie). Ez nemcsak yardveszteséget okoz a támadóknak, hanem egy kísérletükbe (down) is kerül. Egy sack jelentősen visszavetheti a támadássorozatot, és mentálisan is megterhelő az irányító számára.", 2),
        ("Screen Pass", "A 'screen pass' egy rövid, cseles passzjáték, amely a védelem agresszivitását használja ki. A támadófal szándékosan átengedi a védőket, akik az irányítóra rohannak. Az irányító az utolsó pillanatban egy rövid passzt ejt a rohanó védők mögé, általában egy futójátékosnak. A futó előtt ekkor már a támófalemberek blokkolják az utat, így nagy teret nyerhet. Ez a játék időzítést és pontos végrehajtást igényel.", 2),
        ("Special Teams", "A 'special teams' a csapat harmadik, specializált egysége a támadók (offense) és a védők (defense) mellett. Ők lépnek pályára a rúgójátékoknál: kezdőrúgásnál (kickoff), puntnál, mezőnygól- (field goal) és extra pont kísérleteknél. A tagjai gyakran a csapat fiatal, vagy cserejátékosai, de a rúgók (kicker) és a punterek magasan specializálódott profik. A special teams játéka gyakran észrevétlen, de egy-egy nagy visszahordás vagy blokkolt rúgás megváltoztathatja a meccs kimenetelét.", 2),
        ("Trenches (Árkok)", "Az 'árkok' a pálya azon területe, ahol a támadófal (Offensive Line) és a védőfal (Defensive Line) minden játék elején összecsap. Ez a fizikai küzdelem a játék alapja, bár a laikus nézők számára gyakran rejtve marad. Az a csapat, amelyik dominálni tud az 'árkokban', általában a futójátékot is uralja, és az irányítójának is több ideje van passzolni. A meccsek sorsa gyakran itt, a láthatatlan háborúban dől el.", 2),
        ("Turnover (Labdavesztés)", "A 'turnover' az a helyzet, amikor a támadó csapat akaratán kívül elveszíti a labdát, és az az ellenfélhez kerül. Két fő formája van: a 'fumble', amikor a játékos elejti a labdát, és az 'interception', amikor a passzát az ellenfél kapja el. A turnoverök a legköltségesebb hibák közé tartoznak, mert nemcsak a saját támadási lehetőséget szüntetik meg, de azonnali támadási jogot adnak az ellenfélnek, gyakran kedvező mezőnypozícióból.", 2),
        
        # === Játékosok (category_id = 3) ===
        ("Center (C)", "A Center a támadófal 'kapitánya', a sor közepén helyezkedik el. Két kritikus feladata van: ő indítja a játékot a labda hátraadásával (snap), és ő felel a blokkolási sémák bemondásáért és irányításáért. A Centernek egyszerre kell erősnek lennie a védők feltartásához és intelligensnek a védelem felállásának gyors elemzéséhez. Az irányítóval való összhangja, a snap pontossága, elengedhetetlen a sikeres támadójátékhoz.", 3),
        ("Cornerback (CB)", "A cornerback (CB) a védelem egyik legatletikusabb és leggyorsabb játékosa. Elsődleges feladata, hogy az ellenfél elkapóit (Wide Receiver) kövesse, és megakadályozza őket a passzok elkapásában. Ezt 'emberfogásnak' (man coverage) vagy zónavédekezésnek (zone coverage) részeként is végezheti. A jó cornerbackek nemcsak a passzokat ütik le, hanem labdát is szereznek (interception). Ez a pozíció óriási sebességet és gyors irányváltási képességet igényel.", 3),
        ("Defensive End (DE)", "A Defensive End (DE) a védőfal két szélén helyezkedik el. Ők a csapat elsődleges passzsiettetői, céljuk, hogy megkerüljék a támadófal szélén álló játékosokat (offensive tackle) és letámadják az irányítót (sack). Sebességük és erejük kombinációja elengedhetetlen. Emellett a futójátékoknál is fontos szerepük van, meg kell akadályozniuk, hogy a futók a pálya széle felé törjenek ki.", 3),
        ("Defensive Tackle (DT)", "A Defensive Tackle (DT) a védőfal belső, legerősebb és legtestesebb tagja. Az ő feladatuk a futójátékok megállítása a pálya közepén, azzal, hogy feltörik a támadófalat és lezárják a futófolyosókat. Emellett a passzjátékoknál az irányítóra gyakorolt belső nyomással segítik a passzsiettetőket. A DT-k a védelem 'erődítményei', akik a legkeményebb fizikai munkát végzik.", 3),
        ("Fullback (FB)", "A Fullback egy erősebb testalkatú futójátékos, akinek a modern futballban már nem a labdacipelés az elsődleges feladata. Sokkal inkább egyfajta ' faltörő kosként' funkcionál: a másik futójátékos (Running Back) előtt futva blokkolja az utat, utat nyitva a védők között. Emellett a rövid passzoknál is célpont lehet, és a passzvédekezésben is segít blokkolni. Ez egy önfeláldozó, a csapatsikert szolgáló pozíció.", 3),
        ("Guard (G)", "A Guard (G) a támadófal belső embere, a Center és a Tackle között helyezkedik el mindkét oldalon. Elsődleges feladata a passzjátékoknál az irányító előtti 'zseb' fenntartása a belső védőkkel szemben. Futójátékoknál gyakran 'húznak' (pulling), azaz kimozdulnak a helyükről, hogy a sor egy másik pontján vezessék fel a blokkolást a futó számára. Erő és mozgékonyság egyaránt szükséges ehhez a pozícióhoz.", 3),
        ("Kicker (K) - Rúgó", "A rúgó egy magasan specializálódott játékos, aki a speciális csapategység (Special Teams) tagja. Kizárólagos feladata a mezőnygólok (field goal) és az extra pontok elvégzése. Bár egy meccsen keveset van pályán, az ő teljesítménye gyakran döntő fontosságú, különösen a szoros mérkőzések végén. A rúgóknak rendkívül erős lábbal és mentális erővel kell rendelkezniük, hogy a hatalmas nyomás alatt is pontosak maradjanak.", 3),
        ("Linebacker (LB)", "A Linebacker (LB) a védelem 'svájci bicskája', a legsokoldalúbb védőjátékos. A védőfal mögött helyezkednek el, és egyszerre kell képesnek lenniük a futás megállítására, a passzsiettetésre (blitz), és a rövid-középtávú passzok levédekezésére. Ők a védelem vezérei, akik gyakran a legtöbb szerelést hajtják végre a meccsen. Pozíciójuk megköveteli az erőt, a sebességet és a magas szintű játékintelligenciát.", 3),
        ("Long Snapper (LS)", "A Long Snapper (LS) a speciális csapategység egy szinte láthatatlan, de nélkülözhetetlen hőse. Kizárólagos feladata, hogy a puntoknál és a field goal kísérleteknél a labdát nagy távolságra (7-15 yard) és tökéletes pontossággal adja hátra a punternek vagy a labdát tartó játékosnak. Munkája rendkívüli precizitást igényel, mivel egy rossz snap az egész játékot tönkreteheti. Egy csapat sikere gyakran egy megbízható Long Snapperen is múlik.", 3),
        ("Offensive Tackle (OT)", "Az Offensive Tackle (OT) a támadófal két szélén elhelyezkedő játékos. Ők a csapat legfontosabb blokkolói, különösen a passzjátékoknál. A jobbkezes irányító bal oldali tackle-je (Left Tackle) a legértékesebb, mert ő védi az irányító 'holtterét' a láthatatlanul érkező védőktől. A tackle-öknek egyszerre kell nagynak és erősnek lenniük a védők feltartóztatásához, valamint gyors lábúnak és mozgékonynak a passzsiettetők semlegesítéséhez.", 3),
        ("Punter (P)", "A punter a speciális csapategység tagja, aki a labda elrúgásáért felel negyedik kísérletnél. Célja, hogy a labdát a lehető legmagasabbra és legmesszebbre rúgja, úgy, hogy az ellenfél a lehető legmesszebb legyen kénytelen kezdeni a támadását. Egy jó punter képes a labdát pörgetni, és a pálya egy adott pontjára, például az oldalvonal mellé vagy a célterület közelébe rúgni. A mezőnypozíciós csatában a punter kulcsfontosságú fegyver.", 3),
        ("Running Back (RB) - Futójátékos", "A futójátékos egy robbanékony és erős atléta, akinek fő feladata, hogy a labdát cipelve a földön szerezzen teret. Át kell törnie a védők vonalán, ki kell használnia a blokkok által nyitott réseket, és el kell kerülnie a szereléseket. Emellett a passzjátékban is részt vesz, mint blokkoló vagy mint a rövid passzok célpontja. Egy jó futójátékos leveszi a terhet az irányító válláról, és egyensúlyt teremt a támadójátékban.", 3),
        ("Safety (S)", "A Safety (S) a védelem 'utolsó bástyája', a legtávolabb helyezkedik el a kezdővonaltól. Két fő típusa van: a Free Safety (FS), aki a pálya közepét védi a mély passzok ellen, és a Strong Safety (SS), aki gyakran közelebb játszik a vonalhoz és segít a futás elleni védekezésben. A Safetyk feladata, hogy megakadályozzák a nagy, pontszerző játékokat, és besegítsenek a cornerbackeknek. Ők a védelem biztonsági hálója.", 3),
        ("Tight End (TE)", "A Tight End (TE) egy hibrid pozíció a támadósorban, amely ötvözi az elkapók és a támófalemberek képességeit. Felállásuk szerint a támófal szélén helyezkednek el. Képesnek kell lenniük blokkolni a futójátékoknál, mint egy hatodik falember, ugyanakkor elég gyorsnak és ügyesnek kell lenniük ahhoz is, hogy passzútvonalakat fussanak és elkapják a labdát. Sokoldalúságuk miatt a modern támadósorok egyik legértékesebb fegyverévé váltak.", 3),
        ("Wide Receiver (WR) - Elkapó", "Az elkapók a támadósor leggyorsabb és legügyesebb kezű játékosai. Feladatuk, hogy az előre megtervezett útvonalakon fussanak, tisztára játsszák magukat a őket őrző védőktől (cornerbackek), és elkapják az irányító által dobott passzokat. Sebességük és elkapási képességük kulcsfontosságú a nagy, látványos játékokhoz. Gyakran ők szerzik a legtöbb touchdownt, és a támadójáték leglátványosabb elemeit produkálják.", 3),
        
        # === Csapatok (AFC - category_id = 4) ===
        ("Buffalo Bills", "A csapatot 1960-ban alapították, hazai városuk Orchard Park, New York. A gárda a 90-es évek elején egyedülálló módon zsinórban négyszer jutott be a Super Bowlba, de mind a négyet elvesztették. Szurkolótáboruk, a 'Bills Mafia', a liga egyik legszenvedélyesebb és leghíresebb közössége, akik az asztaltöréseikről híresültek el. A csapat színei a piros, fehér és a királykék.", 4),
        ("Miami Dolphins", "Az 1966-ban alapított csapat otthona Miami Gardens, Florida. A Dolphins az NFL történetének egyetlen csapata, amely egy szezont tökéletes mérleggel, veretlenül zárt; ez az 1972-es szezonban történt, amikor megnyerték a Super Bowlt is. Ezt az eredményt azóta egyetlen csapat sem tudta megismételni. A csapat legendás edzője Don Shula, legendás irányítója pedig Dan Marino volt, aki korának egyik legjobb passzoloja volt.", 4),
        ("New England Patriots", "Hazai városuk Foxborough, Massachusetts, és a 21. század legsikeresebb dinasztiájaként tartják őket számon. Tom Brady irányító és Bill Belichick vezetőedző párosa alatt a csapat 6 Super Bowlt nyert 2001 és 2019 között. Ezzel a Pittsburgh Steelers mellett ők a rekordtartók a Super Bowl győzelmek számában. A sikerkorszakuk alapja a fegyelmezett játék és a folyamatosan változó, az ellenfélhez alkalmazkodó stratégia volt.", 4),
        ("New York Jets", "Bár a csapat New Jerseyben, East Rutherfordban játssza hazai meccseit, New York városát képviseli. A Jets történetének legnagyobb pillanata az 1969-es Super Bowl III megnyerése volt. A legendás irányító, Joe Namath vezetésével hatalmas meglepetésre győzték le az akkor favoritnak számító Baltimore Colts csapatát. Ez a győzelem igazolta az AFL (American Football League) létjogosultságát az NFL-lel szemben, és elősegítette a két liga egyesülését.", 4),
        ("Baltimore Ravens", "Az 1996-ban alapított csapat Baltimore városát képviseli, Marylandben. A Ravens a liga egyik legkeményebb és legelismertebb védelméről ismert, ami két Super Bowl győzelemhez is hozzásegítette őket (2001, 2013). Legendás védőik közé tartozik Ray Lewis és Ed Reed. A csapat kabalája és neve Edgar Allan Poe híres költeményére, 'A holló'-ra utal, mivel a költő Baltimore-ban élt és halt meg.", 4),
        ("Cincinnati Bengals", "Az 1968-ban alapított csapat otthona Cincinnati, Ohio. A Bengals könnyen felismerhető jellegzetes, tigriscsíkos sisakjáról és mezeiről. Bár a csapat többször is bejutott a Super Bowlba, a győzelmet még nem sikerült megszerezniük. A 2020-as években Joe Burrow irányítóval egy új, sikeres korszak vette kezdetét a csapat számára.", 4),
        ("Cleveland Browns", "A Browns az NFL egyik legrégebbi és legpatinásabb csapata, 1946-ban alapították. Bár a Super Bowl-érában kevesebb sikert értek el, szurkolótáboruk, a 'Dawg Pound' (Kutyakennel), a liga egyik leghűségesebb és leglelkesebb közössége. A csapatot az 1990-es évek végén Baltimore-ba költöztették (létrehozva a Ravens-t), de a város és a szurkolók kiharcolták, hogy Clevelandben egy új Browns csapat alakulhasson pár évvel később. A csapat nevét az első edzőjükről, Paul Brown-ról kapta.", 4),
        ("Pittsburgh Steelers", "Az 1933-ban alapított Steelers a liga egyik legsikeresebb és legnépszerűbb csapata. A New England Patriots-cal holtversenyben ők nyerték a legtöbb, 6 Super Bowl-t. A csapat a 70-es években egy igazi dinasztia volt, 4 bajnoki címet szerezve. A Steelers a kemény, fizikai védekezéséről és a stabil, családi tulajdonosi hátteréről (Rooney család) ismert. Szurkolóik, a 'Steeler Nation', világszerte megtalálhatók.", 4),
        ("Houston Texans", "A Houston Texans a liga legfiatalabb csapata, 2002-ben alapították, miután a város korábbi csapata, az Oilers, Tennessee-be költözött. A csapat a kezdeti nehézségek után a 2010-es években vált a rájátszás rendszeres résztvevőjévé. Híres játékosaik közé tartozik J.J. Watt, a korszak egyik legdominánsabb védőjátékosa. A csapat színei a sötétkék, a csatavörös és a fehér.", 4),
        ("Indianapolis Colts", "A csapatot eredetileg Baltimore-ban alapították 1953-ban, majd 1984-ben, egy éjszaka leple alatt költöztek Indianapolisba, ami a liga történetének egyik legvitatottabb eseménye volt. A Colts a 2000-es években élte virágkorát Peyton Manning irányító vezetésével, akivel 2007-ben Super Bowl-t nyertek. A csapat jellegzetes fehér-kék meze és patkó logója széles körben ismert.", 4),
        ("Jacksonville Jaguars", "Az 1995-ben, bővítési csapatként alapított Jaguars otthona Jacksonville, Florida. A csapat viszonylag gyorsan sikeres lett, a második szezonjukban már a konferenciadöntőig jutottak. A csapat kabalája, Jaxson de Ville, a liga egyik leglátványosabb és legszórakoztatóbb figurája, aki extrém mutatványairól ismert. A csapat medencével is rendelkezik a stadionjában, ami egyedülálló az NFL-ben.", 4),
        ("Tennessee Titans", "A csapat eredetileg Houston Oilers néven szerepelt, majd 1997-ben költöztek Tennessee-be. A Titans nevet 1999-ben vették fel. Legnagyobb sikerüket a 2000-es Super Bowl XXXIV-en érték el, ahol egyetlen yarddal maradtak le a győzelemről a St. Louis Rams ellen, a meccs utolsó játékában. Ezt a játékot 'The Tackle'-ként emlegetik. A csapat a kemény, futásra épülő támadójátékáról ismert.", 4),
        ("Denver Broncos", "Az 1960-ban alapított csapat otthona Denver, Colorado. A stadionjuk, az Empower Field at Mile High, a tengerszint feletti egy mérföldes magassága miatt hírhedt, ami az oxigénhiány miatt nehézséget okoz a vendégcsapatoknak. A Broncos a 90-es évek végén John Elway irányítóval nyert két Super Bowlt, majd 2016-ban Peyton Manning vezetésével ismét bajnok lett. A csapat narancs és kék színei meghatározóak.", 4),
        ("Kansas City Chiefs", "A csapatot eredetileg Dallas Texans néven alapították, mielőtt 1963-ban Kansas Citybe költöztek. A 2020-as évek elejétől a liga egyik domináns csapatává váltak Patrick Mahomes irányító vezetésével, aki forradalmasította a pozíciót. Stadionjuk, az Arrowhead Stadium, a világ egyik leghangosabb stadionja, ami óriási hazai pályás előnyt jelent. A Chiefs kétszeres Super Bowl győztes a 2020-as években (LIV, LVII).", 4),
        ("Las Vegas Raiders", "A Raiders a liga egyik legikonikusabb és legmegosztóbb csapata, amelyet 1960-ban alapítottak. Történetük során több várost is az otthonuknak mondhattak (Oakland, Los Angeles, és most Las Vegas). A csapat a 'Commitment to Excellence' mottójáról és a kemény, megalkuvást nem tűrő játékstílusáról ismert. Szurkolótáboruk, a 'Raider Nation', az egyik leghűségesebb és legkarakteresebb a sportvilágban. A fekete és ezüst színek elválaszthatatlanok a csapat imázsától.", 4),
        ("Los Angeles Chargers", "A Chargers az AFL egyik alapító tagja volt 1960-ban. A csapat a legtöbb ideig San Diegóban játszott, mielőtt 2017-ben visszaköltözött Los Angelesbe. Jellegzetes, villám logójuk és puskapor kék mezük az egyik legszebb a ligában. A Chargers általában a látványos, passzorientált támadójátékáról ismert, de a csapatsikerek a rájátszásban gyakran elmaradtak.", 4),
        
        # === Csapatok (NFC - category_id = 5) ===
        ("Dallas Cowboys", "Az 1960-ban alapított csapatot gyakran emlegetik 'Amerika Csapataként' (America's Team) hatalmas országos népszerűségük és televíziós jelenlétük miatt. A 90-es években egy dinasztiát építettek fel, három Super Bowl győzelmet aratva Troy Aikman irányító, Emmitt Smith futó és Michael Irvin elkapó nevével fémjelzett trióval. A csillag a logójukban az egyik legismertebb szimbólum a sportvilágban. Jelenlegi otthonuk a lenyűgöző AT&T Stadium Arlingtonban, Texasban.", 5),
        ("New York Giants", "A Giants az NFL egyik legrégebbi csapata, 1925-ben alapították. Bár New York nevét viselik, otthonuk a MetLife Stadium East Rutherfordban, New Jerseyben, amin a Jets-szel osztoznak. A csapat négyszeres Super Bowl győztes, leghíresebb győzelmeiket a 2008-as és 2012-es Super Bowlokon aratták, mindkétszer a favoritnak számító New England Patriots ellen. Ezzel meghiúsították a Patriots veretlen szezonját 2008-ban.", 5),
        ("Philadelphia Eagles", "Az 1933-ban alapított Eagles Philadelphia városát képviseli, és a liga egyik legfanatikusabb és leghangosabb szurkolótáborával rendelkezik. A szurkolók annyira vehemensek, hogy a csapat korábbi stadionjában egy börtön és bíróság is működött a rendbontók számára. Első és eddigi egyetlen Super Bowl győzelmüket 2018-ban szerezték a New England Patriots ellen, a 'Philly Special' nevű legendás trükkös játékkal. A csapat kabalája egy sas, neve Swoop.", 5),
        ("Washington Commanders", "A csapatot 1932-ben alapították Bostonban, majd 1937-ben költöztek Washington D.C. területére. A klub története során több névváltoztatáson is átesett; a leghosszabb ideig Redskins néven szerepeltek, majd ideiglenesen Washington Football Team lettek, mielőtt 2022-ben felvették a Commanders nevet. A csapat három Super Bowl győzelemmel büszkélkedhet, melyeket a 80-as és 90-es években szereztek Joe Gibbs edző vezetésével.", 5),
        ("Chicago Bears", "A Bears az NFL egyik alapító csapata, 1920-ban alapították Decatur Staleys néven. A liga történetének legtöbb győzelmével rendelkeznek, és a Green Bay Packers elleni rivalizálásuk a legrégebbi és legintenzívebb az NFL-ben. A csapatot hagyományosan a kőkemény, domináns védelem jellemzi; a 1985-ös, Super Bowlt nyerő csapatuk védelmét a sportág történetének legjobbjai között tartják számon. A csapat beceneve 'Monsters of the Midway'.", 5),
        ("Detroit Lions", "Az 1929-ben alapított csapat otthona Detroit, Michigan. A Lions egyike annak a négy csapatnak (a Browns, Jaguars és Texans mellett), amely még soha nem jutott el a Super Bowl-ig. Ennek ellenére szurkolótáboruk rendkívül hűséges és kitartó. A csapat hagyományosan minden évben Hálaadás napján játszik hazai mérkőzést, ami egy ikonikus esemény az NFL naptárában. A csapat legendás futójátékosa Barry Sanders volt, aki a 90-es években kápráztatta el a világot.", 5),
        ("Green Bay Packers", "Az 1919-ben alapított Green Bay Packers a liga egyik legpatinásabb csapata, amely Green Bay városában, Wisconsinban található. Ez az egyetlen non-profit, közösségi tulajdonban lévő profi sportcsapat az Egyesült Államokban; a szurkolók a részvényesek. Híresek a 'sajtfejű' (Cheesehead) szurkolóikról, ami utalás Wisconsin állam tejiparárára. A csapat olyan legendás irányítókkal büszkélkedhet, mint Bart Starr, Brett Favre és Aaron Rodgers.", 5),
        ("Minnesota Vikings", "Az 1961-ben alapított csapat otthona Minneapolis, Minnesota. Jellegzetes lila és arany színeik, valamint viking-sisakos logójuk messziről felismerhető. A Vikings a liga egyik legsikeresebb csapata a győzelmi arányt tekintve, azonban a Super Bowl-t még soha nem sikerült megnyerniük, pedig négyszer is bejutottak a döntőbe. Szurkolóik a 'Skol' csatakiáltásukról és a meccsek előtti kürt megfújásáról híresek.", 5),
        ("Atlanta Falcons", "Az 1966-ban alapított Falcons otthona Atlanta, Georgia. A csapat a modern, lenyűgöző Mercedes-Benz Stadiumban játssza hazai meccseit. Történetük leghíresebb és egyben legfájdalmasabb pillanata a 2017-es Super Bowl LI volt. A mérkőzésen a Falcons a sportág történetének legnagyobb, 28-3-as előnyét adta le a New England Patriots ellen, és végül hosszabbításban kikapott.", 5),
        ("Carolina Panthers", "Az 1995-ben, bővítési csapatként alapított Panthers viszonylag fiatalnak számít a ligában, otthonuk Charlotte, North Carolina. A csapatot a fekete, kék és ezüst színek jellemzik, logójuk egy fekete párduc. Kétszer jutottak be a Super Bowlba, de mindkét alkalommal vereséget szenvedtek. Első nagy sikereiket a 2000-es években érték el, majd a 2010-es években Cam Newton irányító vezetésével ismét a liga élvonalába tartoztak.", 5),
        ("New Orleans Saints", "A csapatot 1967-ben, Mindenszentek napján alapították, innen ered a 'Saints' (Szentek) név. A 2005-ös Katrina hurrikán pusztítása után a csapat és a Superdome stadion az újjáépülés és a városi összetartás szimbólumává vált. Néhány évvel később, a 2009-es szezon végén, Drew Brees irányító vezetésével a klub története során először megnyerték a Super Bowlt. A szurkolók híres jelmondata a 'Who Dat?'.", 5),
        ("Tampa Bay Buccaneers", "Az 1976-ban alapított csapat beceneve 'Bucs'. A klub történetének első 26 mérkőzését elvesztette, ami egy NFL rekord. A csapat két Super Bowl győzelemmel büszkélkedhet, melyeket két teljesen különböző korszakban szereztek. Először a 2002-es szezonban egy legendás védelemmel, majd 2021-ben a 43 éves Tom Brady-vel, aki az első ottani szezonjában vezette őket a csúcsra.", 5),
        ("Arizona Cardinals", "A Cardinals a legrégebbi, folyamatosan működő professzionális amerikai futball csapat, 1898-ban alapították Chicagóban. A klub többször is költözött, Chicagóból St. Louisba, majd 1988-ban Arizonába. Bár hosszú a történelmük, kevés sikert értek el; egyetlen Super Bowl szereplésük volt a 2008-as szezonban, ahol drámai körülmények között kikaptak a Pittsburgh Steelerstől. Jelenlegi otthonuk Glendale, Arizona.", 5),
        ("Los Angeles Rams", "A csapatot 1936-ban alapították Clevelandben, majd hosszú időt töltöttek Los Angelesben és St. Louisban, mielőtt 2016-ban visszaköltöztek Los Angelesbe. A Rams nyerte meg a 2022-es Super Bowl LVI-t, amit a saját, ultramodern SoFi Stadiumukban rendeztek meg. A csapat a 90-es évek végén 'The Greatest Show on Turf' néven ismert, rendkívül látványos támadójátékáról volt híres, amellyel megnyerték a Super Bowl XXXIV-et.", 5),
        ("San Francisco 49ers", "Az 1946-ban alapított 49ers a sportág egyik legdicsőbb történelmével rendelkező csapata. A nevüket az 1849-es kaliforniai aranyláz aranyásóiról kapták. A csapat a 80-as és 90-es években egy igazi dinasztia volt, Joe Montana és Steve Young irányítók vezetésével összesen 5 Super Bowl-t nyertek ebben az időszakban. A csapat legendás edzője Bill Walsh volt, a 'West Coast Offense' nevű támadófilozófia megalkotója.", 5),
        ("Seattle Seahawks", "Az 1976-ban alapított csapat otthona Seattle, Washington, és a liga egyik leghangosabb stadionjával büszkélkedhetnek. A szurkolóikat 'a 12. embernek' (The 12th Man) nevezik, utalva arra, hogy a hangzavarukkal aktívan segítik a csapatot, szinte egy plusz játékosként a pályán. A csapat 2014-ben nyerte meg első Super Bowlját egy domináns védelemmel, amit 'Legion of Boom'-ként emlegettek. A csapat színei a tengerészkék, az élénkzöld és a szürke.", 5)
    ]
    cursor.executemany('INSERT INTO entries (term, description, category_id) VALUES (?, ?, ?)', entries_to_add)
    print(f"{len(entries_to_add)} bejegyzés sikeresen hozzáadva az adatbázishoz.")

except sqlite3.Error as e:
    print(f"Hiba történt: {e}")

# Változtatások mentése és kapcsolat bezárása
conn.commit()
conn.close()

print("Az adatbázis újraépítése és feltöltése befejeződött.")